[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build --workspace=packages/api", "npm run build --workspace=packages/web"]

[start]
cmd = "node packages/api/dist/db/migrate.js && node packages/api/dist/index.js"
