// Canonical legal copy for ECS Cornerstone. Kept in sync with
// packages/web/src/pages/legal/content.ts — edit both when the text changes.

export interface LegalSection {
  heading: string;
  body: (string | string[])[];
}

export const CONTACT = 'michael@evertonconsultingservices.org';

export const TERMS_SECTIONS: LegalSection[] = [
  {
    heading: 'Acceptance of Terms',
    body: [
      'By accessing or using the ECS Cornerstone platform, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree, do not use the platform.',
    ],
  },
  {
    heading: 'Description of Service',
    body: [
      'ECS Cornerstone is a behavioral assessment SaaS platform operated by Everton Consulting Services. The platform enables organizations to administer behavioral assessments, generate profile reports, and use the results for workforce development and hiring decisions.',
    ],
  },
  {
    heading: 'Account Registration',
    body: [
      'Organizations must register and provide accurate information. You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account.',
    ],
  },
  {
    heading: 'Acceptable Use',
    body: [
      'You agree not to: misuse assessment data, share assessment links with unauthorized individuals, attempt to reverse engineer the scoring methodology, or use the platform for any unlawful purpose.',
    ],
  },
  {
    heading: 'Assessment Data and Ownership',
    body: [
      'Organizations own the assessment results generated by their employees and candidates. Everton Consulting Services does not sell or share individual assessment data with third parties. Aggregate, anonymized data may be used to improve the platform.',
    ],
  },
  {
    heading: 'Subscription and Billing',
    body: [
      'Subscriptions are billed monthly in advance. Cancellations take effect at the end of the current billing period. No refunds are issued for partial months. Everton Consulting Services reserves the right to modify pricing with 30 days notice.',
    ],
  },
  {
    heading: 'Limitation of Liability',
    body: [
      'The platform is provided "as is." Everton Consulting Services is not liable for indirect, incidental, or consequential damages arising from use of the platform.',
    ],
  },
  {
    heading: 'Termination',
    body: [
      'We reserve the right to terminate accounts that violate these terms. Upon termination, your data will be retained for 30 days and then permanently deleted unless a data export is requested.',
    ],
  },
  {
    heading: 'Governing Law',
    body: ['These terms are governed by the laws of the State of Utah.'],
  },
  {
    heading: 'Contact',
    body: [`Questions about these terms: ${CONTACT}`],
  },
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    heading: 'Information We Collect',
    body: [
      'We collect: account registration information (name, email, company), assessment responses submitted through the platform, usage data (login times, feature usage), and billing information processed by Stripe.',
    ],
  },
  {
    heading: 'How We Use Your Information',
    body: [
      'Assessment data is used solely to generate behavioral profile reports for your organization. We do not use individual assessment responses for marketing or share them with third parties. Billing information is handled entirely by Stripe and is never stored on our servers.',
    ],
  },
  {
    heading: 'Data Storage and Security',
    body: [
      'All data is stored on servers within the United States. Passwords are hashed using bcrypt. Data in transit is encrypted via TLS. PDF reports are stored in AWS S3 with access controlled by signed, time-limited URLs.',
    ],
  },
  {
    heading: 'Data Retention',
    body: [
      'Assessment data is retained for the duration of your subscription plus 30 days after termination. You may request a full data export or deletion at any time by contacting us.',
    ],
  },
  {
    heading: 'Respondent Rights',
    body: [
      `Individuals who complete assessments have the right to request access to their own results. Requests should be directed to your organization's administrator or to ${CONTACT}.`,
    ],
  },
  {
    heading: 'Cookies',
    body: [
      'The platform uses essential session cookies only. We do not use tracking or advertising cookies.',
    ],
  },
  {
    heading: 'Changes to This Policy',
    body: [
      'We will notify account administrators by email of any material changes to this policy with 30 days notice.',
    ],
  },
  {
    heading: 'Contact',
    body: [`Privacy questions: ${CONTACT}`],
  },
];

export const DPA_INTRO =
  'This Data Processing Agreement ("DPA") is entered into between Everton Consulting Services ("Processor") and the subscribing organization ("Controller") and forms part of the ECS Cornerstone Terms of Service.';

export const DPA_SECTIONS: LegalSection[] = [
  {
    heading: 'Definitions',
    body: [
      '"Personal Data" means any information relating to an identified or identifiable natural person submitted to the platform. "Processing" means any operation performed on Personal Data.',
    ],
  },
  {
    heading: 'Scope of Processing',
    body: [
      'Processor will process Personal Data only as necessary to provide the ECS Cornerstone service and as directed by the Controller. Processing activities include: storing assessment responses, scoring assessments, generating PDF reports, and delivering reports via email.',
    ],
  },
  {
    heading: 'Processor Obligations',
    body: [
      'Processor shall: process Personal Data only on documented instructions from Controller; ensure personnel are bound by confidentiality; implement appropriate technical and organizational security measures; assist Controller in responding to data subject rights requests; delete or return all Personal Data upon termination of service.',
    ],
  },
  {
    heading: 'Security Measures',
    body: [
      'Processor maintains the following measures: TLS encryption in transit, bcrypt password hashing, AWS S3 access controls, role-based access control within the platform, and audit logging of administrative actions.',
    ],
  },
  {
    heading: 'Sub-processors',
    body: [
      'Processor uses the following sub-processors: Stripe (payment processing), AWS (cloud storage), SendGrid (email delivery), Railway (hosting). Controller consents to these sub-processors by agreeing to the Terms of Service.',
    ],
  },
  {
    heading: 'Data Transfers',
    body: ['Personal Data is processed and stored within the United States.'],
  },
  {
    heading: 'Term and Termination',
    body: [
      'This DPA is coterminous with the subscription agreement. Upon termination, Processor will delete all Personal Data within 30 days unless retention is required by law.',
    ],
  },
  {
    heading: 'Governing Law',
    body: ['This DPA is governed by the laws of the State of Utah.'],
  },
  {
    heading: 'Execution',
    body: [
      'This DPA is agreed to electronically upon acceptance of the Terms of Service during account registration.',
    ],
  },
];
